In [230]:
import numpy as np
import matplotlib.pyplot as plt
import importlib
import benchmarks
import h5py
import glob
import os
importlib.reload(benchmarks)

In [207]:
(3e-6 * 2.038e8)/(2 * np.pi)

97.30733220638481

In [235]:
physics = {'B0' : '3e-6, 0, 0',
           'L' : '0.2, 0.2, 0.2',
           'yi' : '0.0, 0.0, 1.0',
           'm' : '1.20239e-26',
           't0' : '0.0',
           'tf' : '100.0',
           'T' : '0.45',
           'gamma' : '-2.038e8',
           'a' : '0.0',
           'w' : '0.0',
           'diffuse' : '0.0',
           'gas_coll' : 'true',
           'gravity' : 'false',
           'dist' : 'M'}

integration = {'numParticles' : '65536',
               'numPerGPUBlock' : '256',
               'ioutInt' : '20.0',
               'integratorType' : '0'}

scratch_dir = '/home/rtat/scratch/high_temp_test'

In [238]:
for T, scratch in [(0.35, 'low_temp_test'), (0.4, 'mid_temp_test'), (0.5, 'high_temp_test')]:
    myphysics = physics.copy()
    myphysics['T'] = '{:.2f}'.format(T)
    pb = benchmarks.PignolBenchmark(physics=physics, integration=integration,
                                    E_range = np.linspace(0, 1e7, num=2),
                                    executable='../build/cuda/main', scratch_dir=os.path.join('/home/rtat/scratch', scratch))
    pb.run()

Knudsen Number: 9.42e-03
Adiabaticity: 5.71e+02
Regime: diffusive adiabatic

KeyboardInterrupt:

iter 0, duration 20, 76848
iter 1, duration 40, 76798
iter 2, duration 60, 76765
{0, -0.36852, -0.92962}
231870
iter 0, duration 20, 75646
iter 1, duration 40, 75487
iter 2, duration 60, 75467
{-0.00100459, -0.368031, -0.928416}
227378

In [233]:
data = pb.analyze(files=glob.glob(os.path.join('/home/rtat/scratch/high_temp_test', 'out_*.hdf5')))
data

Knudsen Number: 9.42e-03
Adiabaticity: 5.71e+02
Regime: diffusive adiabatic

,tf,Gxx,Gyy,Gzz,Gxy,Gyz,Gzx,E,sx,sy,sz,tc,phi,phase_error,expected_shift,shift
0,60.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,-0.368520,-0.929620,0.000083,-1.948212,9.947563e-13,0.000000e+00,0.000000e+00
1,60.0,0.0,0.0,0.0,0.0,0.0,0.0,10000000.0,-0.000321,-0.368337,-0.928550,0.000083,-1.948437,3.366569e-05,-1.109557e-06,-3.751333e-06
2,60.0,0.0,0.0,0.0,0.0,0.0,0.0,10000000.0,-0.001005,-0.368031,-0.928416,0.000083,-1.948202,4.030533e-05,-1.109557e-06,1.784141e-07
3,60.0,0.0,0.0,0.0,0.0,0.0,0.0,6670000.0,-0.000215,-0.368438,-0.929144,0.000083,-1.948312,1.496807e-05,-4.936298e-07,-1.668976e-06

In [229]:
data = pb.analyze(files=glob.glob(os.path.join('/home/rtat/scratch/mid_temp_test', 'out_*.hdf5')))
data

Knudsen Number: 2.28e-02
Adiabaticity: 2.50e+02
Regime: diffusive adiabatic

,tf,Gxx,Gyy,Gzz,Gxy,Gyz,Gzx,E,sx,sy,sz,tc,phi,b_rms,expected_shift,shift
0,60.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,-0.368520,-0.929620,0.000213,-1.948212,3.641012e-12,0.000000,0.000000
1,60.0,0.0,0.0,0.0,0.0,0.0,0.0,10000000.0,-0.001986,-0.367407,-0.927135,0.000213,-1.948094,8.466035e-05,-0.000006,0.000002

In [212]:
data = pb.analyze(files=glob.glob(os.path.join('/home/rtat/scratch/low_temp_test', 'out_*.hdf5')))
data

Knudsen Number: 6.20e-02
Adiabaticity: 9.83e+01
Regime: diffusive adiabatic

,tf,Gxx,Gyy,Gzz,Gxy,Gyz,Gzx,E,sx,sy,sz,tc,phi,b_rms,expected_shift,shift
0,60.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,-0.368520,-0.929620,0.000619,-1.948212,1.398996e-10,0.000000,0.000000
1,60.0,0.0,0.0,0.0,0.0,0.0,0.0,10000000.0,-0.003257,-0.368262,-0.926016,0.000619,-1.949305,4.143159e-02,-0.000042,-0.000018
2,60.0,0.0,0.0,0.0,0.0,0.0,0.0,10000000.0,-0.002803,-0.365337,-0.924252,0.000619,-1.947226,5.540663e-02,-0.000042,0.000016
3,60.0,0.0,0.0,0.0,0.0,0.0,0.0,6670000.0,-0.002177,-0.368405,-0.928015,0.000619,-1.948698,2.766082e-02,-0.000019,-0.000008

In [177]:
data['expected_shift']/data['shift']

0         NaN
1    0.774526
2    0.772822
3    0.773463
dtype: float64

In [77]:
phi0_data = data[data['E'] == 0]
data['phi'] - phi0_data['phi'][0]

0    0.000000
1    0.000057
2    0.000006
3    0.000025
Name: phi, dtype: float64

In [91]:
ftest = h5py.File('/home/rtat/scratch/out_0.hdf5')

In [95]:
ftest.attrs.keys()

<KeysViewHDF5 ['B0', 'E', 'Gx', 'Gy', 'Gz', 'L', 'T', 'V', 'a', 'atol', 'beta', 'diffuse', 'dist', 'fac1', 'fac2', 'fixedStepSize', 'gamma', 'gas_coll', 'gravity', 'h', 'hmax', 'hmin', 'integratorType', 'iout', 'ioutInt', 'keepStepSize', 'm', 'maxPosStep', 'nmax', 'numParticles', 'numPerGPUBlock', 'rtol', 'safe', 'seed', 'sqrtKT_m', 'swapStepSize', 't0', 'tc', 'testNoiseAmp', 'testNoiseFreq', 'tf', 'uround', 'w', 'yi']>

In [104]:
ftest.close()